/**
 * Style Dictionary configuration for the ASU Unity Design System.
 *
 * Reads DTCG token JSON from tokens/ and emits:
 *   - src/global/tokens.css          CSS custom properties (--uds-*), the single
 *                                    runtime theming contract for Lit components.
 *   - src/global/generated/_tokens.scss  SCSS variables ($uds-*), the compile-time
 *                                    bridge for legacy Bootstrap/SCSS consumers.
 *
 * Both outputs are generated from the same JSON — do not edit them by hand.
 * Run `yarn build:tokens` (validates first, then builds).
 *
 * Conventions encoded in the custom formats:
 *   - color.semantic.<role>.{light,dark} → `--uds-color-<role>` emitted on
 *     `:root, .uds-surface-light` (light) and `.uds-surface-dark` (dark).
 *   - <path>.{desktop,mobile} → `--uds-<path>` emitted on `:root` (desktop)
 *     and inside `@media (max-width: 767px)` (mobile).
 *   - Pure references ({a.b.c}) are preserved as var()/$ references.
 */

const PREFIX = 'uds';

const isPureRef = (value) =>
  typeof value === 'string' && /^\{[^}]+\}$/.test(value.trim());

const refPath = (value) => value.trim().slice(1, -1);

const originalValue = (token) => token.original.$value ?? token.original.value;
const resolvedValue = (token) => token.$value ?? token.value;

/**
 * Compute the CSS custom property name for a token, applying the
 * semantic-surface and desktop/mobile naming conventions.
 */
function cssInfo(token) {
  let path = [...token.path];
  let bucket = 'base';
  const last = path[path.length - 1];
  if (last === 'light' || last === 'dark') {
    bucket = last;
    path = path.slice(0, -1);
    path = path.filter((seg) => seg !== 'semantic');
  } else if (last === 'desktop' || last === 'mobile') {
    bucket = last === 'desktop' ? 'base' : 'mobile';
    path = path.slice(0, -1);
  }
  return { name: `--${PREFIX}-${path.join('-')}`, bucket };
}

function buildPathMap(dictionary) {
  const map = new Map();
  for (const token of dictionary.allTokens) {
    map.set(token.path.join('.'), token);
  }
  return map;
}

function cssValue(token, pathMap) {
  const orig = originalValue(token);
  if (isPureRef(orig)) {
    const target = pathMap.get(refPath(orig));
    if (target) return `var(${cssInfo(target).name})`;
  }
  return resolvedValue(token);
}

const HEADER = (what) => `/**
 * Do not edit directly — this file is generated by Style Dictionary
 * from tokens/*.json (${what}).
 * Regenerate with: yarn build:tokens
 */
`;

function formatCssThemed({ dictionary }) {
  const pathMap = buildPathMap(dictionary);
  const buckets = { base: [], light: [], dark: [], mobile: [] };
  for (const token of dictionary.allTokens) {
    const { name, bucket } = cssInfo(token);
    if (bucket === 'mobile') {
      // Only emit a mobile override when it differs from the desktop value.
      const desktopPath = [...token.path.slice(0, -1), 'desktop'].join('.');
      const desktop = pathMap.get(desktopPath);
      if (desktop && originalValue(desktop) === originalValue(token)) continue;
      buckets.mobile.push(`    ${name}: ${cssValue(token, pathMap)};`);
      continue;
    }
    buckets[bucket].push(`  ${name}: ${cssValue(token, pathMap)};`);
  }
  let out = HEADER('CSS custom properties');
  out += `\n:root {\n${buckets.base.join('\n')}\n}\n`;
  out += `\n:root,\n.uds-surface-light {\n${buckets.light.join('\n')}\n}\n`;
  out += `\n.uds-surface-dark {\n${buckets.dark.join('\n')}\n}\n`;
  if (buckets.mobile.length) {
    out += `\n@media (max-width: 767px) {\n  :root {\n${buckets.mobile.join('\n')}\n  }\n}\n`;
  }
  return out;
}

function formatScssVariables({ dictionary }) {
  const scssName = (token) => `$${PREFIX}-${token.path.join('-')}`;
  const pathMap = buildPathMap(dictionary);
  // Emit tokens in dependency order so SCSS references resolve.
  const emitted = new Set();
  const lines = [];
  let pending = [...dictionary.allTokens];
  while (pending.length) {
    const next = [];
    for (const token of pending) {
      const orig = originalValue(token);
      if (isPureRef(orig)) {
        const target = pathMap.get(refPath(orig));
        if (target && !emitted.has(target.path.join('.'))) {
          next.push(token);
          continue;
        }
        const value = target ? scssName(target) : resolvedValue(token);
        lines.push(`${scssName(token)}: ${value};`);
      } else {
        lines.push(`${scssName(token)}: ${resolvedValue(token)};`);
      }
      emitted.add(token.path.join('.'));
    }
    if (next.length === pending.length) {
      // Unresolvable cycle — emit resolved values to avoid an infinite loop.
      for (const token of next) {
        lines.push(`${scssName(token)}: ${resolvedValue(token)};`);
      }
      break;
    }
    pending = next;
  }
  return `${HEADER('SCSS variables')}\n${lines.join('\n')}\n`;
}

export default {
  source: ['tokens/**/*.json'],
  usesDtcg: true,
  hooks: {
    formats: {
      'css/uds-themed': formatCssThemed,
      'scss/uds-variables': formatScssVariables,
    },
  },
  platforms: {
    css: {
      transforms: ['name/kebab'],
      buildPath: 'src/global/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/uds-themed',
        },
      ],
    },
    scss: {
      transforms: ['name/kebab'],
      buildPath: 'src/global/generated/',
      files: [
        {
          destination: '_tokens.scss',
          format: 'scss/uds-variables',
        },
      ],
    },
  },
};
