nodeLinker: node-modules

npmMinimalAgeGate: 1w

npmScopes:
  asu:
    npmAuthToken: "${GITHUB_AUTH_TOKEN-fallback}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.17.0.cjs
