const glob = require('glob');


module.exports = {
  plugins: {
    "postcss-import": {},
    "postcss-preset-env": {
      stage: 1,
      features: {
        "nesting-rules": true
      }
    },
    '@fullhuman/postcss-purgecss': {
      content: glob.sync("packages/**/*.js"),
      rejected: true,
      whitelist: [
        // these styles are dynamically generated by the CarouselConrols component
        // in reactstrap:
        "carousel-control-prev",
        "carousel-control-prev-icon",
        "carousel-control-next",
        "carousel-control-next-icon"
      ]
    }
  }
};
