export default { title: 'Components/Anchor Menu' };
import './anchor-menu';

export const AnchorMenu = () => `
  <div class="container" style="height: 5000px">
    <div class="row">
      <div class="col-md-12 pb-5">
        <div  class="my-2">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consectetur lectus nec laoreet elementum. Mauris ut sapien nibh. Aenean consequat pellentesque rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam sollicitudin neque vel risus volutpat, nec hendrerit nisl tempus. Etiam suscipit purus imperdiet, ultrices enim et, maximus lectus. Aenean hendrerit, nibh eget vehicula sollicitudin, nulla tellus accumsan justo, quis gravida sapien quam ultricies magna. Nulla ullamcorper odio id risus pretium, sed ornare turpis luctus. Integer ac semper ex, ac convallis lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In eleifend lobortis lacus sed efficitur. Ut rhoncus consectetur accumsan.
          Nulla massa lorem, maximus eu venenatis in, ultrices sit amet purus. Duis et rutrum mi, id dictum risus. Fusce suscipit metus congue, fermentum sem non, molestie sem. Donec tortor quam, imperdiet vel dui at, finibus vestibulum neque. Nulla facilisi. Sed fermentum vulputate enim, at aliquam diam tincidunt vitae. Nunc eleifend volutpat pellentesque. Aliquam consectetur enim ac lectus dapibus bibendum. Cras eget erat magna. Donec turpis quam, efficitur in leo in, elementum interdum lorem. Duis tempor tempor nulla, at faucibus leo commodo vel. Nunc in tincidunt diam, ac ultrices mauris. Nunc quis vehicula tellus. Mauris vehicula gravida eros, eget facilisis elit viverra faucibus.
          Sed viverra rhoncus erat, eget dignissim orci tincidunt et. Nullam sodales elit eu metus lobortis, ut posuere lectus convallis. Maecenas id lectus id ligula bibendum congue ac ut risus. Integer eget neque volutpat, mollis nisi sed, lobortis mauris. In est metus, rhoncus in tristique nec, blandit sed mauris. Maecenas non risus mauris. Nunc pretium urna sit amet sapien venenatis mollis. Sed facilisis libero nisi, fermentum malesuada magna commodo at. Phasellus sed hendrerit ipsum. Donec ultrices sodales posuere. Proin a finibus mauris, non ornare arcu. Donec eget cursus augue.
          Nulla vel porta massa. Ut hendrerit mauris a suscipit ullamcorper. Donec sagittis tellus non ultrices feugiat. Mauris sodales, eros id vulputate porttitor, nunc augue aliquet tortor, eget mattis turpis mauris nec enim. Proin ac rhoncus lacus. Aliquam venenatis lorem ac arcu commodo tristique id eget dolor. Nam gravida nisi vel purus interdum, faucibus suscipit arcu placerat. Phasellus congue velit et quam elementum, a fermentum velit efficitur. Nunc lobortis, lacus at faucibus vestibulum, mauris nisl facilisis odio, at elementum nisi mauris nec tortor. Nullam commodo pellentesque ante ac porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat neque magna. Suspendisse potenti. Duis dictum ac elit at elementum. In sit amet hendrerit lacus.
        </div>

        <div id="uds-anchor-menu" class="uds-anchor-menu uds-anchor-menu-expanded-lg sticky-top">
          <button class="btn" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            On this page: <span class="fas fa-chevron-down"></span>
          </button>
          <div class="separator"></div>
          <div id="collapseExample" class="card card-body collapse">
            <nav class="nav" aria-label="Same Page">
              <a class="nav-link" href="#first"></span>Live long</a>
              <a class="nav-link" href="#second"><span class="fas fa-hand-spock"></span>Prosper</a>
              <a class="nav-link" href="#third"><span class="fa fa-lightbulb"></span>To boldly go</a>
              <a class="nav-link" href="#fourth"><span class="fa fa-lightbulb"></span>Where no one</a>
              <a class="nav-link" href="#fifth">Has gone before</a>
            </nav>
          </div>
        </div>

        <div id="first" class="my-2">
          First. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consectetur lectus nec laoreet elementum. Mauris ut sapien nibh. Aenean consequat pellentesque rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam sollicitudin neque vel risus volutpat, nec hendrerit nisl tempus. Etiam suscipit purus imperdiet, ultrices enim et, maximus lectus. Aenean hendrerit, nibh eget vehicula sollicitudin, nulla tellus accumsan justo, quis gravida sapien quam ultricies magna. Nulla ullamcorper odio id risus pretium, sed ornare turpis luctus. Integer ac semper ex, ac convallis lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In eleifend lobortis lacus sed efficitur. Ut rhoncus consectetur accumsan.
          Nulla massa lorem, maximus eu venenatis in, ultrices sit amet purus. Duis et rutrum mi, id dictum risus. Fusce suscipit metus congue, fermentum sem non, molestie sem. Donec tortor quam, imperdiet vel dui at, finibus vestibulum neque. Nulla facilisi. Sed fermentum vulputate enim, at aliquam diam tincidunt vitae. Nunc eleifend volutpat pellentesque. Aliquam consectetur enim ac lectus dapibus bibendum. Cras eget erat magna. Donec turpis quam, efficitur in leo in, elementum interdum lorem. Duis tempor tempor nulla, at faucibus leo commodo vel. Nunc in tincidunt diam, ac ultrices mauris. Nunc quis vehicula tellus. Mauris vehicula gravida eros, eget facilisis elit viverra faucibus.
          Sed viverra rhoncus erat, eget dignissim orci tincidunt et. Nullam sodales elit eu metus lobortis, ut posuere lectus convallis. Maecenas id lectus id ligula bibendum congue ac ut risus. Integer eget neque volutpat, mollis nisi sed, lobortis mauris. In est metus, rhoncus in tristique nec, blandit sed mauris. Maecenas non risus mauris. Nunc pretium urna sit amet sapien venenatis mollis. Sed facilisis libero nisi, fermentum malesuada magna commodo at. Phasellus sed hendrerit ipsum. Donec ultrices sodales posuere. Proin a finibus mauris, non ornare arcu. Donec eget cursus augue.
          Nulla vel porta massa. Ut hendrerit mauris a suscipit ullamcorper. Donec sagittis tellus non ultrices feugiat. Mauris sodales, eros id vulputate porttitor, nunc augue aliquet tortor, eget mattis turpis mauris nec enim. Proin ac rhoncus lacus. Aliquam venenatis lorem ac arcu commodo tristique id eget dolor. Nam gravida nisi vel purus interdum, faucibus suscipit arcu placerat. Phasellus congue velit et quam elementum, a fermentum velit efficitur. Nunc lobortis, lacus at faucibus vestibulum, mauris nisl facilisis odio, at elementum nisi mauris nec tortor. Nullam commodo pellentesque ante ac porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat neque magna. Suspendisse potenti. Duis dictum ac elit at elementum. In sit amet hendrerit lacus.
        </div>

        <div id="second" class="my-2">
          Second. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consectetur lectus nec laoreet elementum. Mauris ut sapien nibh. Aenean consequat pellentesque rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam sollicitudin neque vel risus volutpat, nec hendrerit nisl tempus. Etiam suscipit purus imperdiet, ultrices enim et, maximus lectus. Aenean hendrerit, nibh eget vehicula sollicitudin, nulla tellus accumsan justo, quis gravida sapien quam ultricies magna. Nulla ullamcorper odio id risus pretium, sed ornare turpis luctus. Integer ac semper ex, ac convallis lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In eleifend lobortis lacus sed efficitur. Ut rhoncus consectetur accumsan.
          Nulla massa lorem, maximus eu venenatis in, ultrices sit amet purus. Duis et rutrum mi, id dictum risus. Fusce suscipit metus congue, fermentum sem non, molestie sem. Donec tortor quam, imperdiet vel dui at, finibus vestibulum neque. Nulla facilisi. Sed fermentum vulputate enim, at aliquam diam tincidunt vitae. Nunc eleifend volutpat pellentesque. Aliquam consectetur enim ac lectus dapibus bibendum. Cras eget erat magna. Donec turpis quam, efficitur in leo in, elementum interdum lorem. Duis tempor tempor nulla, at faucibus leo commodo vel. Nunc in tincidunt diam, ac ultrices mauris. Nunc quis vehicula tellus. Mauris vehicula gravida eros, eget facilisis elit viverra faucibus.
          Sed viverra rhoncus erat, eget dignissim orci tincidunt et. Nullam sodales elit eu metus lobortis, ut posuere lectus convallis. Maecenas id lectus id ligula bibendum congue ac ut risus. Integer eget neque volutpat, mollis nisi sed, lobortis mauris. In est metus, rhoncus in tristique nec, blandit sed mauris. Maecenas non risus mauris. Nunc pretium urna sit amet sapien venenatis mollis. Sed facilisis libero nisi, fermentum malesuada magna commodo at. Phasellus sed hendrerit ipsum. Donec ultrices sodales posuere. Proin a finibus mauris, non ornare arcu. Donec eget cursus augue.
          Nulla vel porta massa. Ut hendrerit mauris a suscipit ullamcorper. Donec sagittis tellus non ultrices feugiat. Mauris sodales, eros id vulputate porttitor, nunc augue aliquet tortor, eget mattis turpis mauris nec enim. Proin ac rhoncus lacus. Aliquam venenatis lorem ac arcu commodo tristique id eget dolor. Nam gravida nisi vel purus interdum, faucibus suscipit arcu placerat. Phasellus congue velit et quam elementum, a fermentum velit efficitur. Nunc lobortis, lacus at faucibus vestibulum, mauris nisl facilisis odio, at elementum nisi mauris nec tortor. Nullam commodo pellentesque ante ac porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat neque magna. Suspendisse potenti. Duis dictum ac elit at elementum. In sit amet hendrerit lacus.
        </div>

        <div id="third" class="my-2">
          Third. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consectetur lectus nec laoreet elementum. Mauris ut sapien nibh. Aenean consequat pellentesque rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam sollicitudin neque vel risus volutpat, nec hendrerit nisl tempus. Etiam suscipit purus imperdiet, ultrices enim et, maximus lectus. Aenean hendrerit, nibh eget vehicula sollicitudin, nulla tellus accumsan justo, quis gravida sapien quam ultricies magna. Nulla ullamcorper odio id risus pretium, sed ornare turpis luctus. Integer ac semper ex, ac convallis lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In eleifend lobortis lacus sed efficitur. Ut rhoncus consectetur accumsan.
          Nulla massa lorem, maximus eu venenatis in, ultrices sit amet purus. Duis et rutrum mi, id dictum risus. Fusce suscipit metus congue, fermentum sem non, molestie sem. Donec tortor quam, imperdiet vel dui at, finibus vestibulum neque. Nulla facilisi. Sed fermentum vulputate enim, at aliquam diam tincidunt vitae. Nunc eleifend volutpat pellentesque. Aliquam consectetur enim ac lectus dapibus bibendum. Cras eget erat magna. Donec turpis quam, efficitur in leo in, elementum interdum lorem. Duis tempor tempor nulla, at faucibus leo commodo vel. Nunc in tincidunt diam, ac ultrices mauris. Nunc quis vehicula tellus. Mauris vehicula gravida eros, eget facilisis elit viverra faucibus.
          Sed viverra rhoncus erat, eget dignissim orci tincidunt et. Nullam sodales elit eu metus lobortis, ut posuere lectus convallis. Maecenas id lectus id ligula bibendum congue ac ut risus. Integer eget neque volutpat, mollis nisi sed, lobortis mauris. In est metus, rhoncus in tristique nec, blandit sed mauris. Maecenas non risus mauris. Nunc pretium urna sit amet sapien venenatis mollis. Sed facilisis libero nisi, fermentum malesuada magna commodo at. Phasellus sed hendrerit ipsum. Donec ultrices sodales posuere. Proin a finibus mauris, non ornare arcu. Donec eget cursus augue.
          Nulla vel porta massa. Ut hendrerit mauris a suscipit ullamcorper. Donec sagittis tellus non ultrices feugiat. Mauris sodales, eros id vulputate porttitor, nunc augue aliquet tortor, eget mattis turpis mauris nec enim. Proin ac rhoncus lacus. Aliquam venenatis lorem ac arcu commodo tristique id eget dolor. Nam gravida nisi vel purus interdum, faucibus suscipit arcu placerat. Phasellus congue velit et quam elementum, a fermentum velit efficitur. Nunc lobortis, lacus at faucibus vestibulum, mauris nisl facilisis odio, at elementum nisi mauris nec tortor. Nullam commodo pellentesque ante ac porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat neque magna. Suspendisse potenti. Duis dictum ac elit at elementum. In sit amet hendrerit lacus.
        </div>

        <div id="fourth" class="my-2">
          Fourth. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consectetur lectus nec laoreet elementum. Mauris ut sapien nibh. Aenean consequat pellentesque rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam sollicitudin neque vel risus volutpat, nec hendrerit nisl tempus. Etiam suscipit purus imperdiet, ultrices enim et, maximus lectus. Aenean hendrerit, nibh eget vehicula sollicitudin, nulla tellus accumsan justo, quis gravida sapien quam ultricies magna. Nulla ullamcorper odio id risus pretium, sed ornare turpis luctus. Integer ac semper ex, ac convallis lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In eleifend lobortis lacus sed efficitur. Ut rhoncus consectetur accumsan.
          Nulla massa lorem, maximus eu venenatis in, ultrices sit amet purus. Duis et rutrum mi, id dictum risus. Fusce suscipit metus congue, fermentum sem non, molestie sem. Donec tortor quam, imperdiet vel dui at, finibus vestibulum neque. Nulla facilisi. Sed fermentum vulputate enim, at aliquam diam tincidunt vitae. Nunc eleifend volutpat pellentesque. Aliquam consectetur enim ac lectus dapibus bibendum. Cras eget erat magna. Donec turpis quam, efficitur in leo in, elementum interdum lorem. Duis tempor tempor nulla, at faucibus leo commodo vel. Nunc in tincidunt diam, ac ultrices mauris. Nunc quis vehicula tellus. Mauris vehicula gravida eros, eget facilisis elit viverra faucibus.
          Sed viverra rhoncus erat, eget dignissim orci tincidunt et. Nullam sodales elit eu metus lobortis, ut posuere lectus convallis. Maecenas id lectus id ligula bibendum congue ac ut risus. Integer eget neque volutpat, mollis nisi sed, lobortis mauris. In est metus, rhoncus in tristique nec, blandit sed mauris. Maecenas non risus mauris. Nunc pretium urna sit amet sapien venenatis mollis. Sed facilisis libero nisi, fermentum malesuada magna commodo at. Phasellus sed hendrerit ipsum. Donec ultrices sodales posuere. Proin a finibus mauris, non ornare arcu. Donec eget cursus augue.
          Nulla vel porta massa. Ut hendrerit mauris a suscipit ullamcorper. Donec sagittis tellus non ultrices feugiat. Mauris sodales, eros id vulputate porttitor, nunc augue aliquet tortor, eget mattis turpis mauris nec enim. Proin ac rhoncus lacus. Aliquam venenatis lorem ac arcu commodo tristique id eget dolor. Nam gravida nisi vel purus interdum, faucibus suscipit arcu placerat. Phasellus congue velit et quam elementum, a fermentum velit efficitur. Nunc lobortis, lacus at faucibus vestibulum, mauris nisl facilisis odio, at elementum nisi mauris nec tortor. Nullam commodo pellentesque ante ac porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat neque magna. Suspendisse potenti. Duis dictum ac elit at elementum. In sit amet hendrerit lacus.
        </div>

        <div id="fifth" class="my-2">
          Fifth. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consectetur lectus nec laoreet elementum. Mauris ut sapien nibh. Aenean consequat pellentesque rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam sollicitudin neque vel risus volutpat, nec hendrerit nisl tempus. Etiam suscipit purus imperdiet, ultrices enim et, maximus lectus. Aenean hendrerit, nibh eget vehicula sollicitudin, nulla tellus accumsan justo, quis gravida sapien quam ultricies magna. Nulla ullamcorper odio id risus pretium, sed ornare turpis luctus. Integer ac semper ex, ac convallis lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In eleifend lobortis lacus sed efficitur. Ut rhoncus consectetur accumsan.
          Nulla massa lorem, maximus eu venenatis in, ultrices sit amet purus. Duis et rutrum mi, id dictum risus. Fusce suscipit metus congue, fermentum sem non, molestie sem. Donec tortor quam, imperdiet vel dui at, finibus vestibulum neque. Nulla facilisi. Sed fermentum vulputate enim, at aliquam diam tincidunt vitae. Nunc eleifend volutpat pellentesque. Aliquam consectetur enim ac lectus dapibus bibendum. Cras eget erat magna. Donec turpis quam, efficitur in leo in, elementum interdum lorem. Duis tempor tempor nulla, at faucibus leo commodo vel. Nunc in tincidunt diam, ac ultrices mauris. Nunc quis vehicula tellus. Mauris vehicula gravida eros, eget facilisis elit viverra faucibus.
          Sed viverra rhoncus erat, eget dignissim orci tincidunt et. Nullam sodales elit eu metus lobortis, ut posuere lectus convallis. Maecenas id lectus id ligula bibendum congue ac ut risus. Integer eget neque volutpat, mollis nisi sed, lobortis mauris. In est metus, rhoncus in tristique nec, blandit sed mauris. Maecenas non risus mauris. Nunc pretium urna sit amet sapien venenatis mollis. Sed facilisis libero nisi, fermentum malesuada magna commodo at. Phasellus sed hendrerit ipsum. Donec ultrices sodales posuere. Proin a finibus mauris, non ornare arcu. Donec eget cursus augue.
          Nulla vel porta massa. Ut hendrerit mauris a suscipit ullamcorper. Donec sagittis tellus non ultrices feugiat. Mauris sodales, eros id vulputate porttitor, nunc augue aliquet tortor, eget mattis turpis mauris nec enim. Proin ac rhoncus lacus. Aliquam venenatis lorem ac arcu commodo tristique id eget dolor. Nam gravida nisi vel purus interdum, faucibus suscipit arcu placerat. Phasellus congue velit et quam elementum, a fermentum velit efficitur. Nunc lobortis, lacus at faucibus vestibulum, mauris nisl facilisis odio, at elementum nisi mauris nec tortor. Nullam commodo pellentesque ante ac porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat neque magna. Suspendisse potenti. Duis dictum ac elit at elementum. In sit amet hendrerit lacus.
        </div>
      </div>
    </div>
  </div>

`;
