/**
 * Token category constants for programmatic access.
 *
 * These are placeholder values. In production, this file will be
 * auto-generated by Style Dictionary from the design token source
 * (e.g., Figma Tokens / Tokens Studio JSON → Style Dictionary build).
 */

export const TOKEN_CATEGORIES = {
  COLOR: 'color',
  SPACING: 'spacing',
  TYPOGRAPHY: 'typography',
  RADIUS: 'radius',
  SHADOW: 'shadow',
  MOTION: 'motion',
} as const;

export type TokenCategory = (typeof TOKEN_CATEGORIES)[keyof typeof TOKEN_CATEGORIES];
