const glob = require('glob');

module.exports = {
  plugins: {
    "postcss-import": {},
    "postcss-preset-env": {
      stage: 1,
      features: {
        "nesting-rules": true
      }
    },
    '@fullhuman/postcss-purgecss': {
      content: glob.sync('./src/**/*.{js,jsx}', {follow: true, nodir: true}),
      rejected: true,
      whitelist: [
        // these styles are dynamically generated by the CarouselConrols component
        // in reactstrap:
        "carousel-control-prev",
        "carousel-control-prev-icon",
        "carousel-control-next",
        "carousel-control-next-icon",
        "carousel",
        "carousel-item",
        "carousel-item-left",
        "carousel-item-right",
        "carousel-item-next",
        "carousel-item-prev",
        "carousel-indicators",
        "carousel-inner",
        "slide",
        "btn",
        "btn-primary",
        "btn-secondary",
        "jumbotron",
        "jumbotron-fluid",
        "sr-only",
        "active"
      ]
    }
  }
};
